spring.datasource.url=jdbc:postgresql://localhost:5433/samoprodej
spring.datasource.username=devDB
spring.datasource.password=devPass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port= 8082
spring.application.name=samoprodej
