jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDLJKmyTai1uNP8CRTzjfk6Hh8P
    /NljrdO4QltB2Q3nuBdvOiA2TZsWlKsbnU7s6EHXw5oJP8zNrsncuVjoz/1pQVKv2ZWd4SwacZCk
    DtbVChE2j6mOXd2bN2cyaQmgDXDA0p7ThDV3ViL7zntmjuME3EKfcUHmiPa44vuVXUb5ttUJo6pZ
    /iQVptXS2zjAHYfNjALUPJXkZQMxOj3jODCyI+grcpr4cjh3X9k/g5s7zVj5YR1BazOXzgK6pXlW
    NSWczgkZHn+V74jm6TTY4mOhxO54GZ7KK+sjTJQMi/j2cMm5lH4XR/fDtSJMxTXYUeA2Xu25nvju
    OAXK26Y2ixXJAgMBAAECggEABDJSUqGF0xY5w97EqOjljYiug9gpfgSK54cwZy52mfM8wbKZ1IFb
    KzbgR4pjBWQhaxWKfrcrkhKyrx2Bm5KjZaugq4sTSw8KKBQxRKBdWgqSkzXZzvv7rl+RQVJ37U9l
    xUf8mbpFF/1mrNzFwhdA05qAwlY2wi5RaX2f7KSgCRvPQvLixLuNE7DB9mV9awkr3bbekmPnmGee
    OAZ6jp7OUIwoA1Og222sSCSWNHKqNoLPQ0W3CKuYYdWmwYmsAAB/RqbeJ9/uN1CdN7/BSCp6TCHC
    aDmEYk4l/xWn9qhGJmgeS3Dwvja90+b0YwDsPoxEhIQ+++o6j5kU06J0pMxxIQKBgQDdTEvugTi0
    LLR6GX+2dxFnyEMqBAL4752PLLvaN47mmE/bb+0GjN8U1vjOETgeqaR7CdS0D/YfvFNCZOnuABc1
    AexeVSSy0nN6rXzvfVReE6DW0Gm/Bz6/I3c09btIZw+TN1RGzt19t6PK0pXQIkWTFZJL67amrFUI
    7HuoTP6oYQKBgQDq/5DwUdIqZgL+Htvc8pgXcFWIVNmtiYzWJnHYxHswLSr+oAe7ODVWAXnpBT2I
    4CdZiSmCAkeFdu0brORDAF3YkBONLMLIM+e7/1TFYmhIPCMv1mfh3/4PzhMlgAtd3w2A/23ehlI3
    7yGelPQMTVzQ9mTe2VSmJnEyAi1bxP3GaQKBgHr8Wf605hSL+8kXvrhjN9MbougIzrYWRNQ7IjNG
    SS6yWz8y1uGbDKeCSUgMncm8seKHNiTT8g71FLiDaNaSSlN1PC241+phtzfojtRyLJ8T/YEk1oAJ
    wL9tMGTIZEr6q9c/GqE3ejTSCD9CBWxkf5IcnO+AkkPS5ndNJfQExkpBAoGBAIJewgPxAI1xBpwA
    dq0/EM2ADpORrymtM6rirSo65rS1ejLEiUV+S2ipbP6vX5H9+RadF5/+r7sFXUmLQx9Aps+sLoyV
    loIG+bq8TkUq8PuSEVtKsVsILySJiOm2/ZdYVV+JVWSsVBSf36DgtfvVN3beGtve6i07CnVZ69wL
    j1ZxAoGBAMc/z6jKlTqgiNdzUzRkU76ldZQxYZLN6AqjzYMBh33yNbTSK3qV+lbl8uc3h/6t/iIb
    7Xab6cja082ysHeEaS6qOzboHeQjX9qmG/38AQQnWsIoBgyJb5UvLj07MrThhRRCcf6gzj5qz3EY
    U9TMODLJ2WkMZZsxlu9agWlSmWN2
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyySpsk2otbjT/AkU8435Oh4fD/zZY63T
    uEJbQdkN57gXbzogNk2bFpSrG51O7OhB18OaCT/Mza7J3LlY6M/9aUFSr9mVneEsGnGQpA7W1QoR
    No+pjl3dmzdnMmkJoA1wwNKe04Q1d1Yi+857Zo7jBNxCn3FB5oj2uOL7lV1G+bbVCaOqWf4kFabV
    0ts4wB2HzYwC1DyV5GUDMTo94zgwsiPoK3Ka+HI4d1/ZP4ObO81Y+WEdQWszl84CuqV5VjUlnM4J
    GR5/le+I5uk02OJjocTueBmeyivrI0yUDIv49nDJuZR+F0f3w7UiTMU12FHgNl7tuZ747jgFytum
    NosVyQIDAQAB
    -----END PUBLIC KEY-----
  access-token-expiration: 900000 # 15 mins (in ms)
  refresh-token-expiration: 2592000000 # 30 days (in ms)